#MANEJO Y USO DE SERIALIZACIONES

#SERIALIZACION DE COLECCIONES, OBJETOS
#SE RELACIONA CON EL MANEJO DE ARCHIVOS EXTERNOS

# CONSISTE EN GUARDAR EN UN ARCHIVO o FICHERO EXTERNO UNA COLECCIION, DICCIONARIO U OBJETO

# SE GUARDA DE MANERA CODIFCADO EN CODIGO BINARIO

# PROPOSITO: LA DISTRIBUCION POR INTERNET ES MAS FACIL

# ES MAS FACIL LA DISTRIBUCION DE OBJETO DESARROLLADO EN PYTHON POR INTERNET

# ES MEJOR A LA HORA DE GUARDAR LA INFORMACION EN UN DISPOSITIVO EXTERNO 

# ES MAS SENCILLO GUARDAR UN OBJETO COLECCION O DICCIONARIO EN UNA BASE DE DATOS

# PARA SERIALIZAR SE DEBE USAR LA BIBLIOTECA Pickle:
# METODOS A USAR :
# dump() --> volcado de datos al fichero binario externo
# load() --> carga de los datos del fichero binario externo







